# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: processes.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'processes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fprocesses.proto\x12\tprocesses\"0\n\nProcessMsg\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\ttimestemp\x18\x02 \x01(\x05\x32K\n\tProcesses\x12>\n\x0e\x45xecuteProcess\x12\x15.processes.ProcessMsg\x1a\x15.processes.ProcessMsgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'processes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSMSG']._serialized_start=30
  _globals['_PROCESSMSG']._serialized_end=78
  _globals['_PROCESSES']._serialized_start=80
  _globals['_PROCESSES']._serialized_end=155
# @@protoc_insertion_point(module_scope)
