# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lamport_pb2 as lamport__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lamport_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrackerStub:
    """Serviço de rastreamento de frota usado como cenário de teste para os
    Relógios Lógicos de Lamport. O timestamp lógico (Lamport) é o único
    usado pelo algoritmo de ordenação; o gps_time é um relógio FÍSICO
    simulado (com drift proposital) incluído só para evidenciar, no
    relatório, que a ordenação causal não depende dele.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendLocation = channel.unary_unary(
                '/lamport.Tracker/SendLocation',
                request_serializer=lamport__pb2.LocationUpdate.SerializeToString,
                response_deserializer=lamport__pb2.Ack.FromString,
                _registered_method=True)
        self.SendAlert = channel.unary_unary(
                '/lamport.Tracker/SendAlert',
                request_serializer=lamport__pb2.GeofenceAlert.SerializeToString,
                response_deserializer=lamport__pb2.Ack.FromString,
                _registered_method=True)


class TrackerServicer:
    """Serviço de rastreamento de frota usado como cenário de teste para os
    Relógios Lógicos de Lamport. O timestamp lógico (Lamport) é o único
    usado pelo algoritmo de ordenação; o gps_time é um relógio FÍSICO
    simulado (com drift proposital) incluído só para evidenciar, no
    relatório, que a ordenação causal não depende dele.
    """

    def SendLocation(self, request, context):
        """P1 -> P2: leitura de posição do veículo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendAlert(self, request, context):
        """P2 -> P3: alerta de saída de geofence.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLocation,
                    request_deserializer=lamport__pb2.LocationUpdate.FromString,
                    response_serializer=lamport__pb2.Ack.SerializeToString,
            ),
            'SendAlert': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAlert,
                    request_deserializer=lamport__pb2.GeofenceAlert.FromString,
                    response_serializer=lamport__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lamport.Tracker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lamport.Tracker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Tracker:
    """Serviço de rastreamento de frota usado como cenário de teste para os
    Relógios Lógicos de Lamport. O timestamp lógico (Lamport) é o único
    usado pelo algoritmo de ordenação; o gps_time é um relógio FÍSICO
    simulado (com drift proposital) incluído só para evidenciar, no
    relatório, que a ordenação causal não depende dele.
    """

    @staticmethod
    def SendLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lamport.Tracker/SendLocation',
            lamport__pb2.LocationUpdate.SerializeToString,
            lamport__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendAlert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lamport.Tracker/SendAlert',
            lamport__pb2.GeofenceAlert.SerializeToString,
            lamport__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
