# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: processes.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'processes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fprocesses.proto\x12\tprocesses\"D\n\x07Process\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"\x16\n\x14GetProcesssesRequest\">\n\x15GetProcesssesResponse\x12%\n\tprocesses\x18\x01 \x03(\x0b\x32\x12.processes.Process\"#\n\x15GetProcessByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"=\n\x16GetProcessByIdResponse\x12#\n\x07process\x18\x01 \x01(\x0b\x32\x12.processes.Process\";\n\x14\x43reateProcessRequest\x12#\n\x07process\x18\x01 \x01(\x0b\x32\x12.processes.Process\"<\n\x15\x43reateProcessResponse\x12#\n\x07process\x18\x01 \x01(\x0b\x32\x12.processes.Process\";\n\x14UpdateProcessRequest\x12#\n\x07process\x18\x01 \x01(\x0b\x32\x12.processes.Process\"<\n\x15UpdateProcessResponse\x12#\n\x07process\x18\x01 \x01(\x0b\x32\x12.processes.Process\";\n\x14\x44\x65leteProcessRequest\x12#\n\x07process\x18\x01 \x01(\x0b\x32\x12.processes.Process\"<\n\x15\x44\x65leteProcessResponse\x12#\n\x07process\x18\x01 \x01(\x0b\x32\x12.processes.Process2\xb2\x03\n\tProcesses\x12R\n\rGetProcessses\x12\x1f.processes.GetProcesssesRequest\x1a .processes.GetProcesssesResponse\x12U\n\x0eGetProcessById\x12 .processes.GetProcessByIdRequest\x1a!.processes.GetProcessByIdResponse\x12R\n\rCreateProcess\x12\x1f.processes.CreateProcessRequest\x1a .processes.CreateProcessResponse\x12R\n\rUpdateProcess\x12\x1f.processes.UpdateProcessRequest\x1a .processes.UpdateProcessResponse\x12R\n\rDeleteProcess\x12\x1f.processes.DeleteProcessRequest\x1a .processes.DeleteProcessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'processes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESS']._serialized_start=30
  _globals['_PROCESS']._serialized_end=98
  _globals['_GETPROCESSSESREQUEST']._serialized_start=100
  _globals['_GETPROCESSSESREQUEST']._serialized_end=122
  _globals['_GETPROCESSSESRESPONSE']._serialized_start=124
  _globals['_GETPROCESSSESRESPONSE']._serialized_end=186
  _globals['_GETPROCESSBYIDREQUEST']._serialized_start=188
  _globals['_GETPROCESSBYIDREQUEST']._serialized_end=223
  _globals['_GETPROCESSBYIDRESPONSE']._serialized_start=225
  _globals['_GETPROCESSBYIDRESPONSE']._serialized_end=286
  _globals['_CREATEPROCESSREQUEST']._serialized_start=288
  _globals['_CREATEPROCESSREQUEST']._serialized_end=347
  _globals['_CREATEPROCESSRESPONSE']._serialized_start=349
  _globals['_CREATEPROCESSRESPONSE']._serialized_end=409
  _globals['_UPDATEPROCESSREQUEST']._serialized_start=411
  _globals['_UPDATEPROCESSREQUEST']._serialized_end=470
  _globals['_UPDATEPROCESSRESPONSE']._serialized_start=472
  _globals['_UPDATEPROCESSRESPONSE']._serialized_end=532
  _globals['_DELETEPROCESSREQUEST']._serialized_start=534
  _globals['_DELETEPROCESSREQUEST']._serialized_end=593
  _globals['_DELETEPROCESSRESPONSE']._serialized_start=595
  _globals['_DELETEPROCESSRESPONSE']._serialized_end=655
  _globals['_PROCESSES']._serialized_start=658
  _globals['_PROCESSES']._serialized_end=1092
# @@protoc_insertion_point(module_scope)
