# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import processes_pb2 as processes__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in processes_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProcessesStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProcessses = channel.unary_unary(
                '/processes.Processes/GetProcessses',
                request_serializer=processes__pb2.GetProcesssesRequest.SerializeToString,
                response_deserializer=processes__pb2.GetProcesssesResponse.FromString,
                _registered_method=True)
        self.GetProcessById = channel.unary_unary(
                '/processes.Processes/GetProcessById',
                request_serializer=processes__pb2.GetProcessByIdRequest.SerializeToString,
                response_deserializer=processes__pb2.GetProcessByIdResponse.FromString,
                _registered_method=True)
        self.CreateProcess = channel.unary_unary(
                '/processes.Processes/CreateProcess',
                request_serializer=processes__pb2.CreateProcessRequest.SerializeToString,
                response_deserializer=processes__pb2.CreateProcessResponse.FromString,
                _registered_method=True)
        self.UpdateProcess = channel.unary_unary(
                '/processes.Processes/UpdateProcess',
                request_serializer=processes__pb2.UpdateProcessRequest.SerializeToString,
                response_deserializer=processes__pb2.UpdateProcessResponse.FromString,
                _registered_method=True)
        self.DeleteProcess = channel.unary_unary(
                '/processes.Processes/DeleteProcess',
                request_serializer=processes__pb2.DeleteProcessRequest.SerializeToString,
                response_deserializer=processes__pb2.DeleteProcessResponse.FromString,
                _registered_method=True)


class ProcessesServicer:
    """Missing associated documentation comment in .proto file."""

    def GetProcessses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcessById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProcessses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcessses,
                    request_deserializer=processes__pb2.GetProcesssesRequest.FromString,
                    response_serializer=processes__pb2.GetProcesssesResponse.SerializeToString,
            ),
            'GetProcessById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcessById,
                    request_deserializer=processes__pb2.GetProcessByIdRequest.FromString,
                    response_serializer=processes__pb2.GetProcessByIdResponse.SerializeToString,
            ),
            'CreateProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProcess,
                    request_deserializer=processes__pb2.CreateProcessRequest.FromString,
                    response_serializer=processes__pb2.CreateProcessResponse.SerializeToString,
            ),
            'UpdateProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProcess,
                    request_deserializer=processes__pb2.UpdateProcessRequest.FromString,
                    response_serializer=processes__pb2.UpdateProcessResponse.SerializeToString,
            ),
            'DeleteProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProcess,
                    request_deserializer=processes__pb2.DeleteProcessRequest.FromString,
                    response_serializer=processes__pb2.DeleteProcessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'processes.Processes', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('processes.Processes', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Processes:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProcessses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/processes.Processes/GetProcessses',
            processes__pb2.GetProcesssesRequest.SerializeToString,
            processes__pb2.GetProcesssesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProcessById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/processes.Processes/GetProcessById',
            processes__pb2.GetProcessByIdRequest.SerializeToString,
            processes__pb2.GetProcessByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/processes.Processes/CreateProcess',
            processes__pb2.CreateProcessRequest.SerializeToString,
            processes__pb2.CreateProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/processes.Processes/UpdateProcess',
            processes__pb2.UpdateProcessRequest.SerializeToString,
            processes__pb2.UpdateProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/processes.Processes/DeleteProcess',
            processes__pb2.DeleteProcessRequest.SerializeToString,
            processes__pb2.DeleteProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
