syntax = "proto3";
package processes;

service Processes {
  rpc GetProcessses (GetProcesssesRequest) returns (GetProcesssesResponse);
  rpc GetProcessById (GetProcessByIdRequest) returns (GetProcessByIdResponse);
  rpc CreateProcess (CreateProcessRequest) returns (CreateProcessResponse);
  rpc UpdateProcess (UpdateProcessRequest) returns (UpdateProcessResponse);
  rpc DeleteProcess (DeleteProcessRequest) returns (DeleteProcessResponse);
}

message Process {
  string id = 1;
  string name = 2;
  string email = 3;
  string password = 4;
}

message GetProcesssesRequest {

}

message GetProcesssesResponse {
  repeated Process processes = 1;
}

message GetProcessByIdRequest {
  string id = 1;
}

message GetProcessByIdResponse {
  Process process = 1;
}

message CreateProcessRequest {
  Process process = 1;
}

message CreateProcessResponse {
  Process process = 1;
}

message UpdateProcessRequest {
  Process process = 1;
}

message UpdateProcessResponse {
  Process process = 1;
}

message DeleteProcessRequest {
  Process process = 1;
}

message DeleteProcessResponse {
  Process process = 1;
}