services:
  p1:
    build:
      context: .
      dockerfile: ./p1/Dockerfile
    environment:
      PROCESS_ID: P1
    volumes:
      - ./p1/main.py:/app/main.py
      - ./p1/logs:/app/logs
    networks:
      - my_network
    depends_on:
      p2:
        condition: service_healthy

  p2:
    build:
      context: .
      dockerfile: ./p2/Dockerfile
    environment:
      PROCESS_ID: P2
    volumes:
      - ./p2/main.py:/app/main.py
      - ./p2/logs:/app/logs
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50052"]
      interval: 5s

  p3:
    build:
      context: .
      dockerfile: ./p3/Dockerfile
    environment:
      PROCESS_ID: P3
    volumes:
      - ./p3/main.py:/app/main.py
      - ./p3/logs:/app/logs
    networks:
      - my_network

  # logger:
  #   image: my_logger_image
  #   volumes:
  #     - ./logs:/var/log/my_app
  #   networks:
  #     - my_network


networks:
  my_network: