services:
  p1:
    build:
      context: .
      dockerfile: ./proccesses/p1/Dockerfile
    environment:
      PROCESS_ID: P1
    ports:
      - "50051:50051"
    volumes:
      - ./proccesses/process.py:/app/process.py
      - ./proccesses/p1/main.py:/app/main.py
      - ./proccesses/p1/logs:/app/logs
    networks:
      - my_network
    depends_on:
      p2:
        condition: service_healthy
      p3:
        condition: service_healthy
      logger:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import grpc; grpc.channel_ready_future(grpc.insecure_channel('localhost:50051')).result(timeout=3)"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  p2:
    build:
      context: .
      dockerfile: ./proccesses/p2/Dockerfile
    environment:
      PROCESS_ID: P2
    volumes:
      - ./proccesses/process.py:/app/process.py
      - ./proccesses/p2/main.py:/app/main.py
      - ./proccesses/p2/logs:/app/logs
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "python", "-c", "import grpc; grpc.channel_ready_future(grpc.insecure_channel('localhost:50052')).result(timeout=3)"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  p3:
    build:
      context: .
      dockerfile: ./proccesses/p3/Dockerfile
    environment:
      PROCESS_ID: P3
    volumes:
      - ./proccesses/process.py:/app/process.py
      - ./proccesses/p3/main.py:/app/main.py
      - ./proccesses/p3/logs:/app/logs
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "python", "-c", "import grpc; grpc.channel_ready_future(grpc.insecure_channel('localhost:50053')).result(timeout=3)"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  logger:
    build:
      context: .
      dockerfile: ./logger/Dockerfile
    volumes:
      - ./logger/main.py:/app/main.py
      - ./logger/logs:/app/logs
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "python", "-c", "import grpc; grpc.channel_ready_future(grpc.insecure_channel('localhost:50054')).result(timeout=3)"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s


networks:
  my_network:
